In [ ]:
#import data
import pandas as pd
import numpy as np

import glob


#transfer_plate=pd.read_csv("test/transfer_plate.csv",header=0)
arr = pd.read_csv("test/transfer_plate.csv").iloc[:, 1:-4].to_numpy()#I don't know what is up with the last collumn but it shouldnt matter if the convulution isnt padded.
transfer_plate_labels=pd.read_csv("test/transfer_plate.csv").iloc[:, -4:].to_numpy()
test_data = pd.read_csv("test/96_samples.csv",header=None).iloc[:, 1:].to_numpy()

csv_files = glob.glob("*.csv")
dataframes = {}
for file in csv_files:
    
    dataframes[file] = pd.read_csv(file)
    


transfer_plate_labels#here i will assume that the these samples are well placed

array([['sample1', 4.61928175, 1.937171963, 1.052928098],
       ['sample2', 5.782717628, 1.175901957, 1.214737524],
       ['sample3', 3.953447633, 1.350473236, 2.132459339],
       ['sample4', 2.038083652, 0.948045427, 1.380239621],
       ['sample5', 4.978294553, 0.459765296, 2.539621518],
       ['sample6', 4.262552834, 0.336063472, 1.55097026],
       ['sample7', 7.819111584, 0.846057989, 0.785458041],
       ['sample8', 9.390954184, 1.36481141, 1.676221842],
       ['sample9', 6.713935235, 1.853940478, 2.054206282],
       ['sample10', 8.779337413, 1.361967507, 1.81236406],
       ['sample11', 8.605301328, 2.056711184, 0.823049343],
       ['sample12', 11.47050932, 1.445822976, 2.123401956],
       ['sample13', 10.62416263, 0.980751729, 1.429506685],
       ['sample14', 8.608632725, 0.456044771, 1.905153587],
       ['sample15', 4.775166356, 1.56874649, 1.777716209],
       ['sample16', 5.416822914, 1.384659314, 1.306419633],
       ['sample17', 5.98264914, 2.058122288, 2.4440160

In [225]:
transfer_plate_labels_1=[]
for i in range(len(transfer_plate_labels)-1):
    
    transfer_plate_labels_1.append(transfer_plate_labels[i])
    transfer_plate_labels_1.append(transfer_plate_labels[i])
  
transfer_plate_labels_1=np.array(transfer_plate_labels_1)[:192,-3:]
transfer_plate_labels_1=np.array(transfer_plate_labels_1,dtype=np.float32)

#oogga boogga data handling

In [173]:
from scipy.interpolate import interp1d

target_wavenumbers = np.linspace(300, 1942, 1340)
interpolated = []
conc=[]

for file in csv_files:
    # Convert column names to float
    print(file)
    wavelengths = dataframes[file].columns[:-5].astype(float)
    # Get only the spectral data
    intensities_y = (dataframes[file].values)

    conc.append(intensities_y[:,-5:-2])
    #normalization steps --1-- scaling
    
    intensities_y=intensities_y/(np.max(intensities_y))

    print(intensities_y)

    # Interpolate each row (spectrum)
    
    for row in intensities_y:
        
        f = interp1d(wavelengths, row[:-5], kind='quadratic', fill_value='extrapolate')

        interpolated.append(f(target_wavenumbers))
        
    

interpolated=np.array(interpolated)

#normalization step --2--

interpolated=(interpolated-np.mean(interpolated))/np.std(interpolated)

conc=np.vstack(conc)

anton_532.csv
[[6.12906223e-01 6.18048921e-01 6.01548923e-01 ... 1.17462023e-04
  0.00000000e+00 0.00000000e+00]
 [6.04361960e-01 6.11595483e-01 5.97326514e-01 ... 1.17462023e-04
  0.00000000e+00 0.00000000e+00]
 [6.01281558e-01 6.09306579e-01 5.95375892e-01 ... 1.17462023e-04
  0.00000000e+00 0.00000000e+00]
 ...
 [6.31933961e-01 6.37724692e-01 6.22076512e-01 ... 2.83731990e-04
  0.00000000e+00 3.26054705e-04]
 [6.32346420e-01 6.36125394e-01 6.20006880e-01 ... 2.83731990e-04
  0.00000000e+00 3.26054705e-04]
 [6.29817051e-01 6.35774885e-01 6.20083503e-01 ... 2.83731990e-04
  0.00000000e+00 3.26054705e-04]]
anton_785.csv
[[3.30425459e-01 3.28524414e-01 3.25652804e-01 ... 5.27940930e-07
  0.00000000e+00 0.00000000e+00]
 [3.30246520e-01 3.26422957e-01 3.23595724e-01 ... 5.27940930e-07
  0.00000000e+00 0.00000000e+00]
 [3.27078588e-01 3.25612722e-01 3.24311479e-01 ... 5.27940930e-07
  0.00000000e+00 0.00000000e+00]
 ...
 [5.16342835e-01 4.81799065e-01 4.48261646e-01 ... 4.98278609e-04
  0.

Now we standardize the weird ones


In [174]:

arr=arr[:,1:-1]/np.max(arr[:,1:-1])#here, the original array has "[" "]" and are strings, fix 

test_data=test_data[:,1:-1]/np.max(test_data[:,1:-1])
np.shape(arr)


(192, 2046)

In [ ]:
wavelengths=np.linspace(65,3350,2046)# fix with fix up


transfer_plate=[]
clean_test=[]
for row in arr:

    
    f = interp1d(wavelengths, row, kind='quadratic', fill_value='extrapolate')
    transfer_plate.append(f(target_wavenumbers))

for row in test_data:
    g = interp1d(wavelengths, row, kind='quadratic', fill_value='extrapolate')
    
    clean_test.append(g(target_wavenumbers))


transfer_plate=(transfer_plate-np.mean(transfer_plate))/np.std(transfer_plate)
clean_test=(clean_test-np.mean(clean_test))/np.std(clean_test)




array([  65.        ,   66.60635697,   68.21271394, ..., 3346.78728606,
       3348.39364303, 3350.        ])

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import importlib
import Data_augment
importlib.reload(Data_augment)

from torch.utils.data import Dataset , DataLoader
from Data_augment import sinusoidal_noise ,left_right_shift 



class RamanDataset(Dataset):
    def __init__(self, spectra, targets, train=True):

        if isinstance(spectra, np.ndarray) and spectra.dtype == object:
            spectra = np.stack(spectra)  # fix object array
        self.spectra = torch.tensor(spectra, dtype=torch.float32)
        

        self.targets = None if targets is None else torch.tensor(targets, dtype=torch.float32)
        self.train = train

    def __len__(self):
        return len(self.spectra)

    def __getitem__(self, idx):
        # Add channel dimension for CNN: (C, L) where C=1 for 1D signal
        spectrum = self.spectra[idx].unsqueeze(0)  
        
        if self.targets is not None:
            target = self.targets[idx]


        # #data augmentation steps
        # if self.train:
        #     #cosign augmentation
        #     spectrum = spectrum + sinusoidal_noise(1340)
        #     spectrum = left_right_shift(torch.linspace(300,1940,1340),spectrum,5)

        if self.targets is not None:
            target = self.targets[idx]
            return spectrum, target
        
        else:
            return spectrum

0


In [226]:
#dataset = RamanDataset(interpolated, conc , train=True)
print(transfer_plate_labels_1)
transfer_plate=np.array(transfer_plate,dtype=np.float32)

dataset = RamanDataset(transfer_plate, transfer_plate_labels_1 , train=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

# Example: iterate
for spectra_batch, targets_batch in loader:
    print(spectra_batch.shape)  # (batch_size, 1, num_points)
    
    print(targets_batch.shape)  # (batch_size, 3)
    break

[[ 4.619282    1.9371719   1.0529281 ]
 [ 4.619282    1.9371719   1.0529281 ]
 [ 5.7827177   1.175902    1.2147375 ]
 [ 5.7827177   1.175902    1.2147375 ]
 [ 3.9534476   1.3504733   2.1324594 ]
 [ 3.9534476   1.3504733   2.1324594 ]
 [ 2.0380836   0.94804543  1.3802396 ]
 [ 2.0380836   0.94804543  1.3802396 ]
 [ 4.9782944   0.4597653   2.5396216 ]
 [ 4.9782944   0.4597653   2.5396216 ]
 [ 4.2625527   0.33606347  1.5509703 ]
 [ 4.2625527   0.33606347  1.5509703 ]
 [ 7.8191113   0.846058    0.785458  ]
 [ 7.8191113   0.846058    0.785458  ]
 [ 9.390954    1.3648114   1.6762218 ]
 [ 9.390954    1.3648114   1.6762218 ]
 [ 6.7139354   1.8539405   2.0542064 ]
 [ 6.7139354   1.8539405   2.0542064 ]
 [ 8.779338    1.3619676   1.8123641 ]
 [ 8.779338    1.3619676   1.8123641 ]
 [ 8.605301    2.0567112   0.82304937]
 [ 8.605301    2.0567112   0.82304937]
 [11.47051     1.445823    2.1234019 ]
 [11.47051     1.445823    2.1234019 ]
 [10.624163    0.98075175  1.4295067 ]
 [10.624163    0.98075175

In [227]:


class SimpleRamanCNN(nn.Module):
    def __init__(self, input_length=1340, num_outputs=3):
        super(SimpleRamanCNN, self).__init__()
        
        # Article CNN
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=16, kernel_size=9, padding=4)
        self.pool1 = nn.MaxPool1d(kernel_size=2)
        
        self.conv2 = nn.Conv1d(16, 32, kernel_size=7, padding=3)
        self.pool2 = nn.MaxPool1d(kernel_size=2)
        
        self.conv3 = nn.Conv1d(32, 64, kernel_size=5, padding=2)
        
        # Global average pooling
        self.global_avg_pool = nn.AdaptiveAvgPool1d(1)
        
        # Fully connected layers
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, num_outputs)
        
    def forward(self, x):
        # Input shape: (batch, 1, input_length)
        x = self.pool1(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        
        x = self.global_avg_pool(x)  # Shape: (batch, channels, 1)
        x = torch.flatten(x, 1)      # Shape: (batch, channels)
        
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


In [228]:
model = SimpleRamanCNN()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
criterion = nn.MSELoss()

epochs=100

for epoch in range(epochs):
    running_loss=0
    print(epoch)
    for X_batch, y_batch in loader:
        optimizer.zero_grad()
        preds = model(X_batch)
        loss = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch}: Loss {running_loss/len(loader)}")

0
Epoch 0: Loss 12.358452081680298
1
Epoch 1: Loss 7.424372951189677
2
Epoch 2: Loss 5.146110653877258
3
Epoch 3: Loss 4.3405139446258545
4
Epoch 4: Loss 3.845634619394938
5
Epoch 5: Loss 3.2213766972223916
6
Epoch 6: Loss 3.2556494077046714
7
Epoch 7: Loss 3.1901586850484214
8
Epoch 8: Loss 3.1428556044896445
9
Epoch 9: Loss 3.1068719228108725
10
Epoch 10: Loss 3.060161908467611
11
Epoch 11: Loss 3.1248390674591064
12
Epoch 12: Loss 3.1968791087468467
13
Epoch 13: Loss 3.1952839692433677
14
Epoch 14: Loss 3.0997872352600098
15
Epoch 15: Loss 3.2008931835492453
16
Epoch 16: Loss 3.118456721305847
17
Epoch 17: Loss 3.0602922439575195
18
Epoch 18: Loss 3.1340326070785522
19
Epoch 19: Loss 3.061172882715861
20
Epoch 20: Loss 3.0988367398579917
21
Epoch 21: Loss 3.0704523722330728
22
Epoch 22: Loss 3.2253373861312866
23
Epoch 23: Loss 3.1420545975367227
24
Epoch 24: Loss 3.045178850491842
25
Epoch 25: Loss 3.101846138636271
26
Epoch 26: Loss 3.2325831254323325
27
Epoch 27: Loss 3.118512749

In [229]:
clean_test=np.array(clean_test,dtype=np.float32)



In [230]:
test_loader = DataLoader(RamanDataset(clean_test,None, train=False), batch_size=32, shuffle=False)
sanity_check= DataLoader(RamanDataset(interpolated,None, train=False), batch_size=32, shuffle=False)

model.eval()  # switch to evaluation mode
predictions = []

with torch.no_grad():
    for spectra in test_loader:
        outputs = model(spectra)  # shape (batch, 3)
        predictions.append(outputs)

predictions = torch.cat(predictions).numpy()
predictions

array([[8.936371 , 1.540566 , 2.2048864],
       [8.952938 , 1.5425146, 2.2084045],
       [8.439057 , 1.4874697, 2.09876  ],
       [8.44164  , 1.487784 , 2.0993133],
       [8.980466 , 1.5454786, 2.214272 ],
       [8.99685  , 1.547246 , 2.2177715],
       [8.923221 , 1.5391525, 2.2020707],
       [8.9418125, 1.5412496, 2.2060356],
       [8.788187 , 1.525033 , 2.1732404],
       [8.784266 , 1.5246392, 2.1723998],
       [9.054694 , 1.553712 , 2.2300875],
       [9.080652 , 1.5564604, 2.2356362],
       [8.78356  , 1.5242577, 2.172273 ],
       [8.689324 , 1.5141853, 2.1521702],
       [9.055243 , 1.5537729, 2.2302017],
       [9.098289 , 1.5583899, 2.239393 ],
       [7.0439706, 1.3376766, 1.8014987],
       [7.046061 , 1.3379481, 1.8019707],
       [8.938761 , 1.5412221, 2.2053618],
       [9.119444 , 1.5607653, 2.243912 ],
       [6.7192464, 1.3028827, 1.7323984],
       [6.7528043, 1.3063418, 1.7395462],
       [6.6134257, 1.2916512, 1.7098716],
       [6.6292496, 1.2932996, 1.71

In [232]:
#load predictions to sample_submission.csv

template= pd.read_csv("test/sample_submission.csv")


averaged = predictions.reshape(-1, 2, 3).mean(axis=1)

template[['Glucose', 'Sodium Acetate', 'Magnesium Sulfate']] = averaged

# Save to new CSV
template.to_csv("test/sample_submission.csv", index=False)

Now we apply CV to fine tune hiperparameters

In [170]:
import torch
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import KFold

# === Your Dataset Class ===
class RamanDataset(Dataset):
    def __init__(self, spectra, targets, augment=False):
        self.spectra = spectra  # Tensor: shape [N, length]
        self.targets = targets  # Tensor: shape [N]
        self.augment = augment

    def __len__(self):
        return len(self.spectra)

    def __getitem__(self, idx):
        spectrum = self.spectra[idx]
        label = self.targets[idx]

        if self.augment:
            spectrum = spectrum + sinusoidal_noise(len(spectrum))  # your noise fn
            spectrum = left_right_shift(torch.linspace(300,1940,1340), spectrum, maxshift=5)  # example

        spectrum = spectrum.unsqueeze(0)

        return spectrum, label


# === K-fold cross validation setup ===
def run_kfold_cv(spectra, targets, k=5, batch_size=32, epochs=10):
    kfold = KFold(n_splits=k, shuffle=True, random_state=42)
    all_val_losses = []

    for fold, (train_idx, val_idx) in enumerate(kfold.split(spectra)):
        print(f"\n---- Fold {fold+1}/{k} ----")


        train_dataset = RamanDataset(spectra[train_idx], targets[train_idx], augment=True)
        val_dataset   = RamanDataset(spectra[val_idx], targets[val_idx], augment=False)

        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
        val_loader   = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

        # Create model
        model = SimpleRamanCNN()  # replace with your model class
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
        criterion = torch.nn.CrossEntropyLoss()

        # Training loop
        for epoch in range(epochs):
            model.train()
            for X, y in train_loader:
                optimizer.zero_grad()
                out = model(X)
                loss = criterion(out, y)
                loss.backward()
                optimizer.step()

            # Validation loop
            model.eval()
            val_loss = 0
            with torch.no_grad():
                for X, y in val_loader: 
                    out = model(X)
                    val_loss += criterion(out, y).item()

            avg_val_loss = val_loss / len(val_loader)
            print(f"Epoch {epoch+1}/{epochs} - Val Loss: {avg_val_loss:.4f}")

        all_val_losses.append(avg_val_loss)

    print(f"\nAverage Val Loss across folds: {sum(all_val_losses)/len(all_val_losses):.4f}")


# === Example call ===
# spectra, targets = your Raman data as tensors
# wavelengths = your x-axis tensor for augmentation

spectra = torch.tensor(interpolated, dtype=torch.float32)
targets = torch.tensor(conc, dtype=torch.float32)
run_kfold_cv(spectra, targets, k=5, batch_size=32, epochs=10)


---- Fold 1/5 ----
Epoch 1/10 - Val Loss: 4.2600
Epoch 2/10 - Val Loss: 4.2167
Epoch 3/10 - Val Loss: 4.2029
Epoch 4/10 - Val Loss: 4.1979
Epoch 5/10 - Val Loss: 4.2144
Epoch 6/10 - Val Loss: 4.2025
Epoch 7/10 - Val Loss: 4.2062
Epoch 8/10 - Val Loss: 4.2229
Epoch 9/10 - Val Loss: 4.1969
Epoch 10/10 - Val Loss: 4.2205

---- Fold 2/5 ----
Epoch 1/10 - Val Loss: 4.4577
Epoch 2/10 - Val Loss: 4.4764
Epoch 3/10 - Val Loss: 4.4408
Epoch 4/10 - Val Loss: 4.4466
Epoch 5/10 - Val Loss: 4.4281
Epoch 6/10 - Val Loss: 4.4366
Epoch 7/10 - Val Loss: 4.4584
Epoch 8/10 - Val Loss: 4.4637
Epoch 9/10 - Val Loss: 4.4088
Epoch 10/10 - Val Loss: 4.4349

---- Fold 3/5 ----
Epoch 1/10 - Val Loss: 3.9646
Epoch 2/10 - Val Loss: 3.9816
Epoch 3/10 - Val Loss: 3.9581
Epoch 4/10 - Val Loss: 3.9908
Epoch 5/10 - Val Loss: 3.9772
Epoch 6/10 - Val Loss: 3.9952
Epoch 7/10 - Val Loss: 3.9418
Epoch 8/10 - Val Loss: 3.9505
Epoch 9/10 - Val Loss: 3.9339
Epoch 10/10 - Val Loss: 3.9453

---- Fold 4/5 ----
Epoch 1/10 - Val 